[workspace]
default-members = ["shipcat_cli"]
members = [
  "raftcat",
  "shipcat_cli",
  "merge",
  "merge_derive",
  "shipcat_filebacked",
  "shipcat_definitions",
]

[profile.release]
debug = false
