{{- if .Values.autoScaling }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
{{- template "chart.shipcatRefs" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
{{ toYaml .Values.autoScaling | indent 2 }}
{{- end }}
