{{- range $k, $v := .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $k }}
  labels:
    app: {{ $.Values.name }}
{{- template "chart.shipcatRefs" $ }}
type: Opaque
data:
  file: {{ $v }}
{{- end }}

{{- if $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name }}-secrets
  labels:
    app: {{ $.Values.name }}
{{- template "chart.shipcatRefs" $ }}
type: Opaque
data:
{{- range $k, $v := $.Values.secrets }}
  {{ $k }}: "{{ $v | b64enc }}"
{{- end }}
{{- end }}
